"""
test_m1_m2_integration.py
Tests verifying seamless end-to-end integration between:
- M1 ( AI/ML Look-alike classification & age proxy)
- M2 ( Satellite preprocessing, geometry & shape features)
- M3 ( Ocean & Drift simulation)
"""

from datetime import datetime
import json
import pytest

from src.drift.pipeline import (
    run_drift_pipeline,
    run_pipeline_from_satellite_output,
    infer_weathering_age,
)


def test_infer_weathering_age():
    """Verify physical weathering age proxy derived from M2 shape morphology."""
    # Stretched, weathered slick
    weathered_features = {
        "aspect_ratio": 3.8,
        "solidity": 0.58,
        "compactness": 0.22,
    }
    age = infer_weathering_age(weathered_features)
    assert age >= 24.0, "Weathered elongated slick should infer age >= 24 hours"

    # Fresh, compact slick
    fresh_features = {
        "aspect_ratio": 1.2,
        "solidity": 0.92,
        "compactness": 0.75,
    }
    fresh_age = infer_weathering_age(fresh_features)
    assert fresh_age <= 12.0, "Fresh compact slick should infer age <= 12 hours"


def test_integration_with_neha_spill_output_and_nidhi_classification():
    """
    Test passing exact output structures from:
    - M2 Neha (create_spill_output)
    - M1 Nidhi (predict_lookalike)
    """
    # Exact structure generated by Neha's src/satellite/output.py
    mock_neha_output = {
        "image_id": "palsar_0",
        "geometry": {
            "type": "Feature",
            "geometry": {
                "type": "Polygon",
                "coordinates": [
                    [[120.0, 130.0], [135.0, 130.0], [135.0, 145.0], [120.0, 145.0], [120.0, 130.0]]
                ]
            },
            "properties": {
                "area_pixels": 225.0,
                "centroid_x": 127.5,
                "centroid_y": 137.5,
            }
        },
        "geometry_summary": {
            "polygon_count": 1,
            "area_pixels": 225.0,
            "centroid": {
                "x": 127.5,
                "y": 137.5,
            },
            "bounding_box": {
                "min_x": 120.0,
                "min_y": 130.0,
                "max_x": 135.0,
                "max_y": 145.0,
            },
        },
        "features": {
            "area_pixels": 225.0,
            "aspect_ratio": 2.6,
            "compactness": 0.45,
            "extent": 0.72,
            "solidity": 0.68,
        },
    }

    # Exact structure generated by Nidhi's src/lookalike/predict.py
    mock_nidhi_lookalike = {
        "class": "oil",
        "confidence": 0.9625,
    }

    # Execute M3 simulation using Neha and Nidhi outputs
    result = run_pipeline_from_satellite_output(
        spill_output=mock_neha_output,
        lookalike_result=mock_nidhi_lookalike,
        scene_center=(7.5, 72.5),
        detection_time=datetime(2025, 1, 2, 0, 0),
        duration_forward_hours=6,
        current_data_path="data/currents/test_currents.nc",
        num_particles=10,
    )

    # 1. Verify M2 (Neha) metadata ingestion
    assert result.image_id == "palsar_0"
    assert result.spill_id == "spill_palsar_0"
    assert result.spill_area_km2 is not None
    assert result.spill_area_km2 > 0.0
    assert result.shape_features["aspect_ratio"] == 2.6
    # Centroid projected around scene center (7.5, 72.5)
    assert 7.4 <= result.detection_lat <= 7.6
    assert 72.4 <= result.detection_lon <= 72.6

    # 2. Verify M1 (Nidhi) AI classification ingestion
    assert result.is_oil_spill is True
    assert result.classification_confidence == 0.9625
    assert result.estimated_age_hours is not None

    # 3. Verify M3 Drift outputs
    assert len(result.backward_trajectory) > 0
    assert len(result.forward_trajectory) > 0
    assert len(result.origin_search_windows) > 0

    # 4. Verify downstream GeoJSON export (M6 Mansi)
    geojson = result.to_geojson()
    assert geojson["type"] == "FeatureCollection"
    assert geojson["image_id"] == "palsar_0"
    det_feature = [f for f in geojson["features"] if f["properties"]["layer"] == "detection_point"][0]
    assert det_feature["properties"]["is_oil_spill"] is True
    assert det_feature["properties"]["classification_confidence"] == 0.9625

    # 5. Verify downstream AIS parameters (M4 Priya)
    ais_filters = result.to_ais_query_filters()
    assert len(ais_filters) > 0
    assert "start_time" in ais_filters[0]
    assert "bbox" in ais_filters[0]